name: Store Form Submission

on:
  workflow_dispatch:
  repository_dispatch:
    types: [form_submission]

jobs:
  store-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Prepare directory
        run: mkdir -p submissions

      - name: Create submission data file
        run: |
          echo "main brnach"
          echo ${{github.ref_name}}
          echo ${{ secrets.BEARER }}
          date=$(date +%s%3N)
          email="${{ github.event.client_payload.email }}"
          filename="submissions/${email}.txt"
          msg="${{ github.event.client_payload.name }}"
          echo -e "$date:$msg" >> $filename
      
      - name: Commit and push data file
        env:
          GITHUB_TOKEN: ${{ secrets.BEARER }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add submissions/
          git commit -m "Add submission for ${{ github.event.client_payload.email }}"
          
          
          max_retries=3
          retry_count=0
          
          # 将 your_command 替换为你实际需要执行的命令
          git pull origin main --rebase
          git push
          
          # 检查命令是否成功执行，若失败则重试
          while [ $? -ne 0 ]; do
            echo "命令失败，重试中..."
            retry_count=$((retry_count + 1))
          
            if [ $retry_count -ge $max_retries ]; then
              echo "已经达到最大重试次数，退出程序"
              exit 1
            fi

            # 可以选择添加一个睡眠时间以避免过于频繁的重试
            sleep 0.1
            
            # 再次尝试执行命令
            git pull origin main --rebase
            git push
          done
          
          echo "命令成功执行"

          
       

