name: Store Form Submission

on:
  workflow_dispatch:
  repository_dispatch:
    types: [form_submission]

jobs:
  store-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Prepare directory
        run: mkdir -p submissions

      - name: Create submission data file
        run: |
          echo "main brnach"
          echo ${{github.ref_name}}
          echo ${{ secrets.BEARER }}
          date=$(date +%s%3N)
          email="${{ github.event.client_payload.email }}"
          filename="submissions/${email}.txt"
          msg="${{ github.event.client_payload.name }}"
          echo -e "$date:$msg" >> $filename
          echo "msg=$msg" >> $GITHUB_ENV
          echo "filename=$filename" >> $GITHUB_ENV
      
      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          echo 'msg'
          echo $msg
          echo 'filename'
          echo $filename
          pwd
          ls

      - name: Execute script
        env:
          GITHUB_TOKEN: ${{ secrets.BEARER }}
        run: chmod +x ./commit.sh && ./commit.sh "Your commit message" "your_file_name.txt"

          
       

